# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - '*'

pool:
  #vmImage: ubuntu-latest
  default
steps:

- bash: |
    sudo chmod -R 777  ./
     sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://192.168.111.134/DVWA/login.php -n DVWA_Login.context -x /tmp/xml_report.xml -U admin
    true
  displayName: 'Owasp Container Scan'



