# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - '*'

pool:
  vmImage: ubuntu-latest
  #default
steps:

- bash: |
    sudo chmod -R 777  ./
    sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://phpsqldemorpsoi.azurewebsites.net/index.php -x xml_report.xml
    true
  displayName: 'Owasp Container Scan'

- powershell: |
    $XslPath = "https://raw.githubusercontent.com/jazzysc/owasp-zap/main/xml_to_nunit.xslt"
    $XmlInputPath = "xml_report.xml"
    $XmlOutputPath = "converted_report.xml"
    $XslTransform = New-Object System.Xml.Xsl.XslCompiledTransform
    $XslTransform.Load($XslPath)
    $XslTransform.Transform($XmlInputPath, $XmlOutputPath)
  displayName: 'PowerShell Script'

- task: PublishTestResults@2
  inputs:
     testResultsFormat: 'NUnit'
     testResultsFiles: 'converted_report.xml'
  displayName: 'Publish Test Results'
