# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - '*'

pool:
  #vmImage: ubuntu-latest
  default
steps:

- bash: |
    sudo chmod -R 777  ./
    sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://phpsqldemorpsoi.azurewebsites.net/index.php -x /tmp/xml_report.xml
    true
  displayName: 'Owasp Container Scan'



- task: PublishTestResults@2
  inputs:
     testResultsFormat: 'NUnit'
     testResultsFiles: 'converted_report.xml'
  displayName: 'Publish Test Results'
